### ISSUE TITLE
[SM] You need bit-shifting and binary operators

### ISSUE THREAD

**Issue by Polymehr** [5hir0kur0/B8E#1]
Please implement the following Operators to SimpleMath:
    <<
    >>
    <
    >
    &
    |
    ^
    ~

**Comment by 5hir0kur0** [comment]
^ can be made using (~op1&~op2|op1&~op2) and it collides with the operator ^ for exponentiation, so I won't add it.

Also, I don't see any reason to add < and >, but I will add them anyway for now.
